apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: account-service
  labels:
    app: account-service
    service: account-service    ###ServiceName
    env: nonprod

    containers:
          image: rahulnallari/microservice-springboot:account-service      #ECS Docker Image repo link
          imagePullPolicy: Always
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            successThreshold: 1
            initialDelaySeconds: 15
            timeoutSeconds: 2
          name: account-service
          ports:
            - name: http
              containerPort: 8080
